#ifndef SALTYSD_SE_ERRORS_H
#define SALTYSD_SE_ERRORS_H

typedef enum {
    PLUGIN_OK = 0,
    PLUGIN_READ = 1,
    PLUGIN_TOO_BIG = 2,
    PLUGIN_EMPTY = 3,
    PLUGIN_NOT_ELF = 4,
    PLUGIN_BAD_SEGMENT = 5,
    PLUGIN_NO_ORIGINAL = 6,
    PLUGIN_MISMATCH = 7,
    PLUGIN_CONFLICT = 8,
    PLUGIN_FULL = 9,
    PLUGIN_INCOMPATIBLE = 10,
    PLUGIN_MULTIPLE = 11,
    PLUGIN_NO_SIGNATURE = 12,
    PLUGIN_SIG_NOT_FOUND = 13,
    PLUGIN_SIG_AMBIGUOUS = 14,
    PLUGIN_BAD_FIXUP = 15,
    PLUGIN_BAD_TARGET = 16,
    PLUGIN_NO_MEMORY = 17,
    SE_ERROR_INVALID_ID = 32,
    SE_ERROR_DUPLICATE_ID = 33,
    SE_ERROR_MISSING_DEPENDENCY = 34,
    SE_ERROR_DEPENDENCY_VERSION = 35,
    SE_ERROR_DEPENDENCY_REFUSED = 36,
    SE_ERROR_DEPENDENCY_CYCLE = 37,
    SE_ERROR_EXPLICIT_CONFLICT = 38,
    SE_ERROR_STATIC_COLLISION = 39,
    SE_ERROR_WRONG_BUILD = 40,
    SE_ERROR_FILE_CHANGED = 41,
    SE_ERROR_ABI_UNSUPPORTED = 42,
    SE_ERROR_CAPABILITY_UNSUPPORTED = 43,
    SE_ERROR_HOOK_UNSUPPORTED = 44,
    SE_ERROR_HOOK_CONFLICT = 45,
    SE_ERROR_HOOK_TARGET_CHANGED = 46,
    SE_ERROR_HOOK_FULL = 47,
} se_error;

const char *se_error_text(se_error error);

#endif
