[package]
id = "org.saltysd.examples.skip-c08-h08-textures"
display_name = "Skip c08/h08 textures"
author = "SALT Engine team"
version = "2.0.2"
abi_min = "1.0"
abi_max = "1.0"
capabilities = []

[payload]
elf = "build/skip_c08_h08_textures.elf"
code = "../../../code.bin"
output = "build/skip_c08_h08_textures.sea"

[[builds]]
id = 0x01170001
title_id = 0x000EDF00
game_version = "1.1"
region = "usa"
code = "../../../code.bin"
variant = 1

[[variants]]
id = 1
