#ifndef SALTYSD_SE_TARGETS_H
#define SALTYSD_SE_TARGETS_H

#include <se/types.h>

typedef enum {
    SE_TARGET_FUNCTION_ARM = 1,
    SE_TARGET_FUNCTION_THUMB = 2,
    SE_TARGET_POINTER_SLOT = 3,
    SE_TARGET_TABLE = 4,
    SE_TARGET_DATA = 5,
    SE_TARGET_PATCH_SITE = 6,
} se_target_kind;

typedef struct {
    se_u32 id;
    se_u32 address;
    se_u32 span;
    se_u16 kind;
    se_u16 flags;
} se_target;

enum {
    SE_TARGET_SMASH_ANIMCMD_HITTEST_HANDLER_SITE = 0x00010000u,
    SE_TARGET_SMASH_ANIMCMD_HITTEST_REMOVE_ALL_SLOT = 0x00010001u,
    SE_TARGET_SMASH_ANIMCMD_HITTEST_HITBOX_SLOT = 0x00010002u,
    SE_TARGET_SMASH_ANIMCMD_HITTEST_EXTENDED_SLOT = 0x00010003u,
    SE_TARGET_SMASH_ANIMCMD_HITTEST_SPECIAL_SLOT = 0x00010004u,
    SE_TARGET_SMASH_ANIMCMD_HITTEST_EXTENDED_SPECIAL_SLOT = 0x00010005u,
};

#endif
