#!/usr/bin/env python3


import os
import sys

BASE = 0x100000

# v1.2's payloads sit here, over libpng.
LIBPNG_LO, LIBPNG_HI = 0xA33000, 0xA37000

GAP = 16

REGIONS = {
    "000EDF00": ("usa", ["USA-bundled", "USA-hosted"]),
    "000EE000": ("eur", ["EUR"]),
    "000B8B00": ("jpn", ["JPN"]),
}


def read_ips(path):
    d = open(path, "rb").read()
    if d[:5] != b"PATCH":
        raise SystemExit(f"{path}: not an IPS file")
    i = 5
    recs = []
    while d[i:i + 3] != b"EOF":
        off = int.from_bytes(d[i:i + 3], "big")
        n = int.from_bytes(d[i + 3:i + 5], "big")
        i += 5
        if n == 0:
            rl = int.from_bytes(d[i:i + 2], "big")
            recs.append((off, bytes([d[i + 2]]) * rl))
            i += 3
        else:
            recs.append((off, d[i:i + n]))
            i += n
    return recs


def apply_ips(image, recs, path):
    out = bytearray(image)
    for off, data in recs:
        if off + len(data) > len(out):
            raise SystemExit(f"{path}: record at 0x{off:06X} runs past the end of the code.bin")
        out[off:off + len(data)] = data
    return bytes(out)


def runs(a, b):
    out = []
    i = 0
    while i < len(a):
        if a[i] != b[i]:
            j = i
            while j < len(a) and a[j] != b[j]:
                j += 1
            if out and i - out[-1][1] < GAP:
                out[-1][1] = j
            else:
                out.append([i, j])
            i = j
        else:
            i += 1
    return out


def simulate(image, variants):
    img = bytearray(image)
    partial = False
    for n, (_name, vruns) in enumerate(variants):
        matched = sum(1 for va, v12, _stock in vruns
                      if img[va - BASE:va - BASE + len(v12)] == v12)
        if matched == len(vruns):
            for va, _v12, stock in vruns:
                img[va - BASE:va - BASE + len(stock)] = stock
            return n + 1, bytes(img)
        if matched:
            partial = True
    return (-1 if partial else 0), bytes(img)


def carray(data):
    return ", ".join(f"0x{x:02X}" for x in data)


def main():
    if len(sys.argv) < 5 or len(sys.argv) % 2 == 0:
        raise SystemExit("usage: gen_legacy.py <v1.2 ips dir> <out.h> <title id> <code.bin> [<title id> <code.bin> ...]")
    ipsdir, out = sys.argv[1:3]
    pairs = list(zip(sys.argv[3::2], sys.argv[4::2]))
    targets = [t for t, _ in pairs]
    for t in targets:
        if t not in REGIONS:
            raise SystemExit(f"no v1.2 IPS is known for title {t}")

    pristines = {}
    variants = []
    images = []
    for t, codebin in pairs:
        stem, names = REGIONS[t]
        pristine = open(codebin, "rb").read()
        pristines[stem] = pristine
        for name in names:
            path = os.path.join(ipsdir, f"{name}.ips")
            patched = apply_ips(pristine, read_ips(path), path)
            vruns = [(i + BASE, patched[i:j], pristine[i:j]) for i, j in runs(pristine, patched)]
            variants.append((name, vruns))
            images.append((name, stem, patched))

    for n, (name, stem, patched) in enumerate(images):
        result, undone = simulate(patched, variants)
        if result != n + 1:
            raise SystemExit(f"{name}: recognised as variant {result}, expected {n + 1}")
        if undone != pristines[stem]:
            raise SystemExit(f"{name}: undoing it does not give back the pristine {stem} code.bin")
    for stem, pristine in pristines.items():
        result, undone = simulate(pristine, variants)
        if result != 0 or undone != pristine:
            raise SystemExit(f"the pristine {stem} code.bin is mistaken for v1.2 (result {result})")

    arrays = {}
    lines = []

    def array(data):
        if data not in arrays:
            arrays[data] = f"lg{len(arrays)}"
            lines.append(f"static const u8 {arrays[data]}[] = {{ {carray(data)} }};\n")
        return arrays[data]

    tables = []
    for n, (name, vruns) in enumerate(variants):
        rows = [f"    {{ 0x{va:08X}, {len(v12)}, {array(v12)}, {array(stock)} }},\n"
                for va, v12, stock in vruns]
        tables.append(f"static const LegacyRun legacy{n + 1}_runs[] = {{\n{''.join(rows)}}};\n")

    with open(out, "w", encoding="utf-8") as f:
        w = f.write
        w("/* Generated by gen_legacy.py - do not edit. */\n#pragma once\n\n")
        w(f"#define SALTYSD_LEGACY_TITLE_ID 0x{targets[0]}\n\n")
        for line in lines:
            w(line)
        w("\n")
        for table in tables:
            w(table)
        w("\nstatic const LegacyVariant legacy_variants[] = {\n")
        for n, (name, vruns) in enumerate(variants):
            w(f"    {{ legacy{n + 1}_runs, {len(vruns)} }},\n")
        w("};\n")

    print(f"wrote {out}: {len(variants)} v1.2 variants, {sum(map(len, arrays))} bytes of tables")
    for n, (name, vruns) in enumerate(variants):
        payload = sum(len(v) for va, v, _ in vruns if LIBPNG_LO <= va < LIBPNG_HI)
        code = sum(len(v) for va, v, _ in vruns) - payload
        print(f"   {n + 1} {name:12s} {len(vruns):3d} runs, {code:5d} bytes of code, {payload:5d} bytes of payload")


if __name__ == "__main__":
    main()
