#!/usr/bin/env python3


import sys

BASE = 0x100000

# The payloads used to be written over live libpng code here.
LIBPNG_LO, LIBPNG_HI = 0xA33000, 0xA37000

# Runs closer together than this are emitted as one.
GAP = 16


def runs(a, b):
    if len(a) != len(b):
        raise SystemExit("the two binaries are different sizes")
    out = []
    i = 0
    while i < len(a):
        if a[i] != b[i]:
            j = i
            while j < len(a) and a[j] != b[j]:
                j += 1
            if out and i - out[-1][1] < GAP:
                out[-1][1] = j
            else:
                out.append([i, j])
            i = j
        else:
            i += 1
    return out


def carray(data):
    return ", ".join(f"0x{x:02X}" for x in data)


def main():
    if len(sys.argv) != 4:
        raise SystemExit('usage: gen_patches.py <pristine code.bin> <patched code.bin> <out.h>')
    pristine = open(sys.argv[1], "rb").read()
    patched = open(sys.argv[2], "rb").read()
    out = sys.argv[3]

    found = runs(pristine, patched)
    total = sum(j - i for i, j in found)

    for i, j in found:
        va = i + BASE
        if LIBPNG_LO <= va < LIBPNG_HI:
            raise SystemExit(
                f"a patch run lands at 0x{va:06X}, inside the old payload range. "
                "The payloads belong in the plugin; check patch.py."
            )

    with open(out, "w", encoding="utf-8") as f:
        w = f.write
        w("/* Generated by tools/gen_patches.py - do not edit.\n"
          f" * {sys.argv[1]}\n"
          f" * -> {sys.argv[2]}\n"
          f" * {len(found)} runs, {total} bytes.\n"
          " */\n#pragma once\n\n")
        for n, (i, j) in enumerate(found):
            w(f"static const u8 p{n}_want[] = {{ {carray(patched[i:j])} }};\n")
            w(f"static const u8 p{n}_orig[] = {{ {carray(pristine[i:j])} }};\n")
        w("\nstatic const SaltyPatch saltysd_patches[] = {\n")
        for n, (i, j) in enumerate(found):
            w(f"    {{ 0x{i + BASE:08X}, {j - i}, p{n}_want, p{n}_orig }},\n")
        w("};\n")

    print(f"wrote {out}: {len(found)} runs, {total} bytes")
    for i, j in found:
        print(f"   0x{i + BASE:06X}-0x{j + BASE:06X}  {j - i:5d}")


if __name__ == "__main__":
    main()
